from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class GuidePoint:
    id: str
    category: str
    title: str
    weight: float
    patterns: tuple[str, ...]

GUIDE: tuple[GuidePoint, ...] = (
    GuidePoint(
        "combat.auto_attack",
        "Бой",
        "автоматическая атака",
        18,
        (
            r"performAttack",
            r"auto.?attack",
            r"canAttackNow",
            r"ATTACK_DELAY",
            r"killaura",
            r"kill.?aura",
            r"auto.?totem",
        ),
    ),
    GuidePoint(
        "combat.aimbot",
        "Бой",
        "аимбот — автоматическое наведение",
        20,
        (r"aimbot", r"aim.?assist", r"auto.?aim", r"rotateTo", r"lookAtEntity"),
    ),
    GuidePoint(
        "combat.triggerbot",
        "Бой",
        "триггербот / таргетбот — удар только по сущностям",
        18,
        (r"triggerbot", r"trigger.?bot", r"targetbot", r"target.?bot", r"isValidTarget", r"entityHitResult"),
    ),
    GuidePoint(
        "combat.autoclicker",
        "Бой",
        "автокликер с боевым функционалом",
        15,
        (
            r"autoclicker",
            r"auto.?click",
            r"criticalsOnly",
            r"COOLDOWN_THRESHOLD",
            r"canPerformCritical",
            r"swordOnly",
            r"TapeMouse",
            r"tapemouse",
        ),
    ),
    GuidePoint(
        "combat.hitreg",
        "Бой",
        "изменение регистрации ударов",
        14,
        (r"hitreg", r"attack.?reach", r"extra.?reach", r"reach.?hack", r"\breachHack\b"),
    ),
    GuidePoint(
        "combat.hitbox",
        "Бой",
        "увеличение или изменение хитбоксов",
        18,
        (
            r"increaseHitbox",
            r"decreaseHitbox",
            r"applyHitboxScale",
            r"enlargedHitbox",
            r"updateHitboxes",
            r"restoreAllHitboxes",
            r"hitboxScale",
            r"hitboxSize",
            r"key\.hitboxmod",
            r"expandHitbox",
            r"expandServerPlayersHitboxes",
            r"hitboxExpansionSize",
            r"increaseHitboxBinding",
            r"decreaseHitboxBinding",
            r"increaseHitboxKey",
            r"decreaseHitboxKey",
            r"hit.?box.?size",
            r"setBoundingBox",
            r"getHitboxScale",
        ),
    ),
    GuidePoint(
        "combat.through_blocks",
        "Бой",
        "атака сквозь траву, цветы и другие мешающие блоки",
        12,
        (r"through.?walls", r"ignore.?blocks", r"wall.?hit", r"attackThrough"),
    ),
    GuidePoint(
        "combat.crystals",
        "Бой",
        "автоматическая работа с кристаллами / ускорение кристаллов",
        16,
        (r"crystal.?aura", r"auto.?crystal", r"AutoCrystal", r"autocrystal", r"crystalSpeed", r"end.?crystal"),
    ),
    GuidePoint(
        "combat.target_select",
        "Бой",
        "автоматический выбор цели",
        12,
        (r"target.?select", r"auto.?target", r"priorityTarget", r"ignoreFriends"),
    ),
    GuidePoint(
        "combat.weapon_swap",
        "Бой",
        "автоматическая смена оружия или предмета во время боя",
        12,
        (r"auto.?weapon", r"weapon.?swap", r"auto.?slot.?swap", r"hotbar.?swap.?combat"),
    ),
    GuidePoint(
        "visual.esp",
        "Отображение",
        "ESP: силуэт игрока / хитбокса (outline, wireframe, filled box)",
        18,
        (
            r"playeresp",
            r"PlayerESP",
            r"storage.?esp",
            r"chest.?esp",
            r"item.?esp",
            r"mob.?esp",
            r"entity.?esp",
            r"box.?esp",
            r"outline.?esp",
            r"wireframe",
            r"filled.?box",
            r"entity.?outline",
        ),
    ),
    GuidePoint(
        "visual.silhouette",
        "Отображение",
        "силуэт хитбокса или игрока (через стены / поверх мира)",
        18,
        (
            r"entity.?silhouette",
            r"player.?silhouette",
            r"hitbox.?esp",
            r"HitboxESP",
            r"hitbox.?outline",
            r"bounding.?box.?esp",
            r"player.?outline.?esp",
            r"through.?wall.?outline",
            r"esp.?silhouette",
            r"customhitboxes",
            r"CustomHitboxes",
            r"renderDebugBoundingBox",
            r"renderBoundingBox",
            r"oldHitbox",
            r"TargetESP",
        ),
    ),
    GuidePoint(
        "visual.hitbox_hp",
        "Отображение",
        "полоски HP размером с хитбокс (горизонтальные или вертикальные)",
        16,
        (
            r"hitbox.?health",
            r"hitbox.?hp",
            r"health.?bar.?hitbox",
            r"hp.?bar.?hitbox",
            r"entity.?health.?bar",
            r"world.?health.?bar",
            r"HealthBarESP",
            r"big.?health.?bar",
            r"vertical.?health.?bar",
            r"horizontal.?health.?bar",
        ),
    ),
    GuidePoint(
        "visual.wall_glow",
        "Отображение",
        "подсветка сущностей через стены",
        16,
        (
            r"FORCED_GLOW",
            r"onIsGlowing",
            r"glowThrough",
            r"EntityOutline",
            r"see.?through.?walls",
            r"wallhack",
        ),
    ),
    GuidePoint(
        "visual.tracers",
        "Отображение",
        "трассеры до игроков",
        12,
        (r"tracer", r"tracers", r"line.?to.?player"),
    ),
    GuidePoint(
        "visual.invis",
        "Отображение",
        "отображение невидимых игроков",
        16,
        (
            r"true.?sight",
            r"show.?invis",
            r"invisible.?player",
            r"anti.?invis",
            r"onIsInvisible",
        ),
    ),
    GuidePoint(
        "bypass.jar_in_jar",
        "Обходы",
        "подложенный nested-jar / маскировка чита внутри легитимного мода",
        22,
        (r"NESTED_SUSPICIOUS:", r"t\.me/ghostbitbox", r"shouldUnload"),
    ),
    GuidePoint(
        "visual.info_hud",
        "Отображение",
        "броня / дистанция / направление до скрытых игроков (не обычный HP-индикатор)",
        10,
        (r"target.?hud", r"armor.?esp", r"distance.?esp", r"direction.?esp"),
    ),
    GuidePoint(
        "visual.xray",
        "Отображение",
        "Xray блоков, руд или сущностей / ресурс-паки Xray",
        16,
        (r"\bxray\b", r"oreEsp", r"OreESP", r"ore[_-]esp", r"cave.?finder"),
    ),
    GuidePoint(
        "visual.minimap",
        "Отображение",
        "мини-карта с запрещённым функционалом",
        10,
        (r"radar", r"player.?radar", r"entity.?radar"),
    ),
    GuidePoint(
        "visual.auto_detect",
        "Отображение",
        "автоматическое обнаружение игроков или объектов вокруг",
        10,
        (r"player.?detect", r"auto.?detect", r"nearby.?players"),
    ),
    GuidePoint(
        "camera.freecam",
        "Камера",
        "Freecam / свободная камера / просмотр сквозь стены",
        18,
        (r"freecam", r"free.?cam", r"free.?look", r"camera.?hack"),
    ),
    GuidePoint(
        "move.step",
        "Передвижение",
        "автоматическое поднятие на блоки без прыжка",
        12,
        (r"auto.?step", r"step.?hack", r"StepModule", r"stepHeight"),
    ),
    GuidePoint(
        "move.altered",
        "Передвижение",
        "автоматизированное или изменённое передвижение",
        14,
        (r"speed.?hack", r"fly.?hack", r"jesus", r"nofall", r"velocity.?mod"),
    ),
    GuidePoint(
        "move.invwalk",
        "Передвижение",
        "хождение с открытым инвентарём",
        10,
        (r"inventory.?walk", r"inv.?walk", r"move.?in.?inventory"),
    ),
    GuidePoint(
        "move.elytra",
        "Передвижение",
        "Elytra Hack / автоматическая смена элитр",
        14,
        (r"elytra.?hack", r"elytra.?swap", r"ElytraSwap", r"elytraswap", r"auto.?elytra", r"firework.?boost"),
    ),
    GuidePoint(
        "combat.shift_tap",
        "Бой",
        "ShiftTap / автоприсед при ударе",
        12,
        (r"shift.?tap", r"ShiftTap", r"shifttap", r"auto.?sneak.?hit", r"w-tap", r"wtap"),
    ),
    GuidePoint(
        "move.path",
        "Передвижение",
        "автоматическое прохождение маршрутов",
        12,
        (r"baritone", r"pathfinder", r"auto.?walk", r"auto.?path"),
    ),
    GuidePoint(
        "inv.auto_tool",
        "Инвентарь",
        "автоматическая смена инструмента / брони / предмета",
        10,
        (r"auto.?tool", r"auto.?armor", r"auto.?totem", r"auto.?hotbar"),
    ),
    GuidePoint(
        "inv.auto_eat",
        "Инвентарь",
        "автоматическое использование еды / AutoEat / AutoSwap",
        10,
        (r"auto.?eat", r"AutoEat", r"autoeat", r"auto.?gap", r"auto.?swap", r"AutoSwap", r"autoswap", r"auto.?pot"),
    ),
    GuidePoint(
        "inv.auto_trade",
        "Инвентарь",
        "автоматическая покупка / продажа / выброс предметов",
        14,
        (
            r"AutoBuyModule",
            r"AutoSellModule",
            r"AutoDropModule",
            r"(?<![A-Za-z])AutoBuy(?![A-Za-z])",
            r"(?<![A-Za-z])AutoSell(?![A-Za-z])",
            r"(?<![A-Za-z])AutoDrop(?![A-Za-z])",
            r"stash.?stealer",
            r"StashStealer",
        ),
    ),
    GuidePoint(
        "search.ores",
        "Поиск",
        "поиск руд / алмазов / контейнеров / хорусов",
        14,
        (r"ore.?finder", r"diamond.?esp", r"chest.?finder", r"shulker.?esp", r"chorus.?esp"),
    ),
    GuidePoint(
        "search.seed",
        "Поиск",
        "поиск структур или координат по сиду",
        14,
        (r"seed.?crack", r"seed.?finder", r"structure.?finder", r"stronghold.?finder"),
    ),
    GuidePoint(
        "search.world_dl",
        "Поиск",
        "копирование чанков / скачивание мира сервера",
        18,
        (r"chunk.?download", r"world.?download", r"wdl\b", r"save.?chunks"),
    ),
    GuidePoint(
        "auto.bot",
        "Автоматизация",
        "боты / макросы / автодобыча / автостроительство",
        14,
        (r"autobot", r"macro", r"auto.?mine", r"auto.?build", r"bedrock.?breaker"),
    ),
    GuidePoint(
        "bypass.proxy",
        "Обходы",
        "клиентские прокси / подмена версии / маскировка читов",
        16,
        (
            r"version.?spoof",
            r"viafabricplus",
            r"selfdestruct",
            r"hide.?cheat",
            r"cloak.?mod",
            r"antidump",
            r"mod.?hider",
        ),
    ),
    GuidePoint(
        "visuals.banned",
        "Запрещённые визуалы",
        "скрытие слепоты / эффект-обходы с преимуществом",
        12,
        (r"no.?blind", r"anti.?blind", r"remove.?blindness", r"no.?nausea", r"no.?darkness"),
    ),
    GuidePoint(
        "known.banned_client",
        "Известные читы",
        "совпадение имени с чёрным списком (слабый сигнал)",
        5,
        (),
    ),
)

LEGIT_BRAND_IDS = {
    "lithium": ("me.jellysquid", "net.caffeinemc"),
    "sodium": ("me.jellysquid", "net.caffeinemc"),
    "iris": ("net.irisshaders",),
    "phosphor": ("me.jellysquid", "net.caffeinemc"),
    "modmenu": ("com.terraformersmc.modmenu",),
    "entityculling": ("dev.tr7zw.entityculling",),
}

LEGIT_NESTED_MOD_IDS = frozenset(
    {
        "transition",
        "trender",
        "entityculling",
        "modmenu",
        "fabric-api",
        "cloth-config",
        "cloth-config2",
        "cloth_config",
    }
)

BANNED_KNOWN_MODS: tuple[str, ...] = (
    "akrien",
    "ares",
    "aristois",
    "armor hotswap",
    "armorhotswap",
    "arbuz",
    "atomic",
    "autoattack",
    "aimbot",
    "autoclicky",
    "bariton",
    "baritone",
    "bedrock breaker",
    "bedrockbreaker",
    "bleachhack",
    "betterhitreg",
    "calestial",
    "celestial",
    "celka",
    "chunk copy",
    "chunkcopy",
    "clean cut",
    "cleancut",
    "clientcommands",
    "clickcrystals",
    "crystal optimizer",
    "crystaloptimizer",
    "camerautils",
    "cutthrough",
    "dauntiblyat",
    "deadcode",
    "delta",
    "diamond sim",
    "diamondsim",
    "doomsday",
    "double hotbar",
    "doublehotbar",
    "dreampool",
    "eclipse",
    "elytra swap",
    "elytraswap",
    "elytra hack",
    "elytrahack",
    "entity outliner",
    "entityoutliner",
    "entity xray",
    "entityxray",
    "expensive",
    "exire",
    "extazyy",
    "feather client",
    "featherclient",
    "forge hax",
    "forgehax",
    "freecam",
    "future",
    "fuzeclient",
    "hakari",
    "hush",
    "huzuni",
    "hach",
    "impact",
    "infinity",
    "inertia",
    "invmove",
    "inventory walk",
    "inventorywalk",
    "inventory profiles next",
    "inventoryprofilesnext",
    "invtweaks",
    "inventorysorter",
    "jex",
    "konas",
    "librarian trade finder",
    "librariantradefinder",
    "liquidbounce",
    "lowdurabilityswitcher",
    "luminex",
    "meteor",
    "minced",
    "mobhitbox",
    "mobhealthbar",
    "moonhack",
    "neverhook",
    "nightware",
    "nodus",
    "nova",
    "nurik",
    "nursultan",
    "nemos inventory",
    "nuclear",
    "ricardo",
    "richclient",
    "rogalik",
    "rusherhack",
    "sacurachorusfind",
    "save searcher",
    "savesearcher",
    "seed cracker",
    "seedcracker",
    "sigma",
    "skill client",
    "skillclient",
    "smart moving",
    "smartmoving",
    "squad",
    "step up",
    "stepup",
    "swingthroughgrass",
    "showinginvisibleplayers",
    "takker",
    "thunderhack",
    "topkaautobuy",
    "troxill",
    "tweakeroo",
    "topkaautodrop",
    "tool swap",
    "toolswap",
    "torohealth",
    "vape",
    "vec.dll",
    "venus",
    "viaforge",
    "viabackwards",
    "viaproxy",
    "wurst",
    "wildclient",
    "winner",
    "worlddownloader",
    "wexside",
    "wissend",
    "xray",
    "zamorozka",
    "zeusclient",
    "zenithclient",
    "autoswap",
    "elytraswap",
    "shifttap",
    "autoeat",
    "autosell",
    "autocrystal",
    "killaura",
    "triggerbot",
    "targetbot",
)

NON_ZPO_MALWARE_PATTERNS = (
    r"discord(app)?\.com/api/webhooks",
    r"api\.telegram\.org",
    r"stealer",
    r"token.?grab",
    r"password.?steal",
    r"exfiltrat",
    r"\bratted\b",
    r"\bratware\b",
    r"Blowfish",
    r"cmd\.exe\s*/C",
    r"javaprogramm\.jar",
)

TRNTR_REPACK_PATTERNS = (
    r"trntr_pth",
    r"xtrs_pth",
    r"TeamCraftMC/thatguy",
    r"thatguy/raw/main/verifier",
)

KNOWN_BUNDLED_LIB_PREFIXES = (
    "me/shedaniel/clothconfig",
    "me/shedaniel/math",
    "com/google/gson",
    "org/spongepowered/asm",
    "net/fabricmc/fabric/api",
)

NON_ZPO_ALLOWED_VISUAL_PATTERNS = (
    r"health.?indicator",
    r"hp.?indicator",
    r"show.?health",
    r"player.?health",
    r"entity.?health",
    r"health.?display",
    r"HealthDisplay",
    r"HealthNumerals",
    r"particle.?esp",
    r"particle.?ring",
    r"circle.?esp",
    r"ring.?esp",
    r"halo.?esp",
    r"foot.?circle",
    r"under.?player",
    r"circle.?under",
    r"fancy.?esp",
)
